services:
  - type: web
    name: medical-rag-api
    env: python
    buildCommand: pip install --upgrade pip && pip install --only-binary=all -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15